get http://localhost:3000/books

###
get http://localhost:3000/books/1


###
post http://localhost:3000/books
Content-Type: application/json

{
    "title":"Personas compran personas",
    "author": "Carlos Rosales",
    "year": 2010 
}


###
put http://localhost:3000/books/3
Content-Type: application/json

{
    "year": 2016
}

###
delete http://localhost:3000/books/4
